api = "0.5"

[buildpack]
id = "paketo-buildpacks/dotnet-publish"
name = "Paketo .NET Publish Buildpack"
version = "{{ .Version }}"
homepage = "https://github.com/paketo-buildpacks/dotnet-publish"

[metadata]
include-files = ["bin/build","bin/detect", "bin/run", "buildpack.toml","go.mod","go.sum"]
pre-package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
