api = "0.2"

[buildpack]
id = "paketo-buildpacks/dotnet-publish"
name = "Paketo .Net Publish Buildpack"
version = "{{ .Version }}"
homepage = "https://github.com/paketo-buildpacks/dotnet-publish"

[metadata]
include_files = ["bin/build","bin/detect", "bin/run", "buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
